### ISSUE TITLE
Cooling not working in 2D 

### ISSUE THREAD

**Issue by twaters** [cholla-hydro/cholla#18] opened 2019-07-30 20:19 UTC
Hi Evan.  In 1D, cooling was working fine.  Just moving to 2D in our branch, the cooling timestep drops to 0 instantly.  We reproduced this on the public branch using the input file constant.txt below.  Compiling with cooling off works and with cooling on doesn't.
[constant.txt](https://github.com/cholla-hydro/cholla/files/3448720/constant.txt)

**Comment by evaneschneider** [comment] 2019-07-30 21:19
I've reproduced the issue on the Princeton cluster - looking into the cause now.

**Comment by twaters** [comment] 2019-07-30 21:37
Awesome...we have a feeling the cause is within the modifications to the CFL condition, but it is unclear why only 2D triggers this.

**Comment by evaneschneider** [comment] 2019-07-30 21:59
Okay, I just pushed a fix. The issue had something to do with the fact that the 2D integrator is the only one where I used 2D grids of thread blocks. I'm not really sure where the problem was; for now, I just fixed it by using 1D Cuda grids in the 2D integrators (the same as the 1D and 3D integrators). The downside is that this means the total number of cells that can be computed in a simulation using a single GPUs is (max_blocks_per_grid_dim * threads_per_block), which is currently 65535*256 = 16,776,960. So, for example, the code would break if you tried to run a 4096*4096 sim on a single card (so close, though!). But I think that use-case is currently unusual enough for it to be worth it to apply this fix at the moment, so you can get on with your sims. Eventually I should fix this once and for all by striding to get a constant total number of blocks, but that's an optimization for another day.

**Comment by twaters** [comment] 2019-07-30 22:12
Thank you, and wow, so close indeed!  It's good to know we can run 4095^2 on a single node!!

**Closed** 2019-08-20 13:20 UTC
